### ISSUE TITLE
SEQUEL DEPRECATION WARNING

### ISSUE THREAD

**Issue by job** [NLNOG/ring-sqa#17]
```
Apr 12 12:01:41 nexellent01 ring-sqad[16108]: SEQUEL DEPRECATION WARNING: The schema plugin is deprecated and will be removed in Sequel 5.  Switch to defining your schema using Database schema methods before creating your model classes.
Apr 12 12:01:41 nexellent01 ring-sqad[16108]: /var/lib/gems/2.3.0/gems/sequel-4.45.0/lib/sequel/plugins/schema.rb:3:in `<top (required)>'
Apr 12 12:01:41 nexellent01 ring-sqad[16108]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Apr 12 12:01:41 nexellent01 ring-sqad[16108]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Apr 12 12:01:41 nexellent01 ring-sqad[16108]: /var/lib/gems/2.3.0/gems/sequel-4.45.0/lib/sequel/model/base.rb:1199:in `plugin_module'
Apr 12 12:01:41 nexellent01 ring-sqad[16108]: /var/lib/gems/2.3.0/gems/sequel-4.45.0/lib/sequel/model/base.rb:739:in `plugin'
Apr 12 12:01:41 nexellent01 ring-sqad[16108]: /var/lib/gems/2.3.0/gems/ring-sqa-0.3.1/lib/ring/sqa/database.rb:46:in `initialize'
Apr 12 12:01:41 nexellent01 ring-sqad[16108]: /var/lib/gems/2.3.0/gems/ring-sqa-0.3.1/lib/ring/sqa/core.rb:23:in `new'
Apr 12 12:01:41 nexellent01 ring-sqad[16108]: /var/lib/gems/2.3.0/gems/ring-sqa-0.3.1/lib/ring/sqa/core.rb:23:in `initialize'
Apr 12 12:01:41 nexellent01 ring-sqad[16108]: /var/lib/gems/2.3.0/gems/ring-sqa-0.3.1/lib/ring/sqa/cli.rb:14:in `new'
Apr 12 12:01:41 nexellent01 ring-sqad[16108]: /var/lib/gems/2.3.0/gems/ring-sqa-0.3.1/lib/ring/sqa/cli.rb:14:in `run'
```

**Comment by job** [comment]
@ytti what does this mean
